"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { GameResult } from "@/lib/simulateGame";
import { gtm } from "@/lib/gtm";
import { useDraftStore } from "@/stores/draftStore";
import ExhibitionMatch from "@/components/cup/ExhibitionMatch";
import { TeamPicker, TeamPick, RANDOM_ID } from "@/components/sim/TeamPicker";
import { SimCrossLinks } from "@/components/sim/SimCrossLinks";
import PostToSimFeedButton from "@/components/sim/PostToSimFeedButton";
import AppHeader from "@/components/layout/AppHeader";

// CTA that drops the user into the Roster Builder to create their own lineup.
// Surfaced on the picker and on result screens to convert simulator play into
// team creation.
function BuildOwnTeamCTA({ className = "" }: { className?: string }) {
  const router = useRouter();
  const { setMode, reset } = useDraftStore();
  const go = () => {
    reset();
    setMode("sandbox");
    gtm.sandboxStart({ team_filter: "Random", season_filter: "Random" });
    router.push("/draft");
  };
  return (
    <button
      onClick={go}
      className={`block w-full py-3 rounded-xl border border-zinc-700 hover:border-orange-500/60 bg-zinc-900 hover:bg-zinc-800 text-zinc-300 hover:text-white font-bold text-sm text-center transition-colors ${className}`}
    >
      🔧 Want a custom contender? Build your own team →
    </button>
  );
}

type SimMeta = { id: string; name: string; overall: number; tier: string };

function PostToTeamButton({ teamId, payload, onPosted }: {
  teamId: string;
  payload: { type: string; result_data: Record<string, unknown> };
  onPosted: () => void;
}) {
  const [posted, setPosted] = useState(false);
  const [posting, setPosting] = useState(false);
  if (posted) return null;
  return (
    <button
      onClick={async () => {
        setPosting(true);
        try {
          await fetch(`/api/teams/${teamId}/simulations`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          });
          setPosted(true);
          onPosted();
        } catch {
          setPosting(false);
        }
      }}
      disabled={posting}
      className="block w-full py-3 rounded-xl bg-orange-500/20 border border-orange-500/40 hover:bg-orange-500/30 text-orange-300 font-bold text-sm text-center transition-colors disabled:opacity-50"
    >
      {posting ? "Posting…" : "📌 Post to Team Page"}
    </button>
  );
}

// Shorten a player name so the points stay visible: first name → initial,
// then hard-cap the remainder so long family names get an ellipsis.
// e.g. "Giannis Antetokounmpo" → "G. Antetokoun…"
function shortScorer(name: string, max = 13, ellipsis = true): string {
  const parts = name.trim().split(/\s+/);
  let s = parts.length >= 2 ? `${parts[0][0]}. ${parts.slice(1).join(" ")}` : name;
  if (s.length > max) s = ellipsis ? `${s.slice(0, max - 1)}…` : s.slice(0, max);
  return s;
}

// Top scorer line from a box score (highest points; first on ties).
function topScorer(box: { name: string; pts: number }[]): { name: string; pts: number } {
  return box.reduce(
    (best, l) => (l.pts > best.pts ? { name: l.name, pts: l.pts } : best),
    { name: "", pts: -1 }
  );
}

// Encode per-game top scorers for the share URL: "hName~hPts~aName~aPts" per
// game, games joined by ",". Names are shortened (first-initial + capped, no
// ellipsis) so the URL stays well under X's character limit.
function encodeTops(games: GameResult[]): string {
  return games
    .map((g) => {
      const h = topScorer(g.homeBox);
      const a = topScorer(g.awayBox);
      return `${shortScorer(h.name, 13, false)}~${h.pts}~${shortScorer(a.name, 13, false)}~${a.pts}`;
    })
    .join(",");
}

// Open the X intent composer. The shared URL points to /matchup/result with the
// result encoded in the query string, so the link carries a rich VS-scoreboard
// OGP image (generated by /api/og?mode=matchup).
function shareToX(
  text: string,
  result: {
    home: string;
    away: string;
    hs: number | string;
    as: number | string;
    kind: "single" | "series";
    /** Per-game scores for a series, e.g. "102-112,117-107,..." */
    games?: string;
    /** Per-game top scorers, e.g. "LeBron~34~Curry~29,..." */
    tops?: string;
  }
) {
  const origin = typeof window !== "undefined" ? window.location.origin : "";
  const qs = new URLSearchParams({
    home: result.home,
    away: result.away,
    hs: String(result.hs),
    as: String(result.as),
    kind: result.kind,
  });
  if (result.games) qs.set("games", result.games);
  if (result.tops) qs.set("tops", result.tops);
  const url = `${origin}/matchup/result?${qs.toString()}`;
  const winner = Number(result.hs) > Number(result.as) ? result.home : result.away;
  const loser = Number(result.hs) > Number(result.as) ? result.away : result.home;
  const subtitle = result.kind === "series" ? "Match · Series" : "Match · Single";
  fetch("/api/sim/feed", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      kind: "matchup",
      result_url: url,
      title: `⚔️ ${winner} def. ${loser}`,
      subtitle,
    }),
  }).catch(() => {});
  const tweetUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
  window.open(tweetUrl, "_blank");
}

type SimResponse =
  | { mode: "single"; home: SimMeta; away: SimMeta; result: GameResult }
  | {
      mode: "series";
      home: SimMeta;
      away: SimMeta;
      games: GameResult[];
      seriesWins: { home: number; away: number };
      seriesWinner: "home" | "away";
    };


function SeriesResult({
  home,
  away,
  games,
  wins,
  winner,
  onReset,
  onRematch,
  sourceTeamId,
}: {
  home: SimMeta;
  away: SimMeta;
  games: GameResult[];
  wins: { home: number; away: number };
  winner: "home" | "away";
  onReset: () => void;
  onRematch: () => void;
  sourceTeamId?: string | null;
}) {
  const router = useRouter();
  const [posted, setPosted] = useState(false);
  const [posting, setPosting] = useState(false);
  const winnerName = winner === "home" ? home.name : away.name;
  return (
    <div className="fixed inset-0 z-50 bg-zinc-950 overflow-y-auto">
      <AppHeader actions={
        <button onClick={onReset} className="text-xs font-bold text-zinc-400 hover:text-white transition-colors">← Back</button>
      } />
      <div className="max-w-lg mx-auto px-4 py-8 space-y-5">
        <div className="text-center">
          <p className="font-display text-xs font-bold text-orange-400 uppercase tracking-[0.3em] mb-2">
            Series Final · Best of 7
          </p>
          <h2 className="font-display text-2xl font-black text-white">🏆 {winnerName}</h2>
          <p className="font-display text-5xl font-black text-white mt-3">
            <span className={winner === "home" ? "text-orange-400" : "text-zinc-500"}>{wins.home}</span>
            <span className="text-zinc-700 mx-3">–</span>
            <span className={winner === "away" ? "text-orange-400" : "text-zinc-500"}>{wins.away}</span>
          </p>
          <div className="flex items-center justify-center gap-3 mt-2 text-sm">
            <span className="text-zinc-300 font-bold truncate max-w-[40%]">{home.name}</span>
            <span className="text-zinc-600">vs</span>
            <span className="text-zinc-300 font-bold truncate max-w-[40%]">{away.name}</span>
          </div>
        </div>

        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl divide-y divide-zinc-800/60">
          {games.map((g, i) => {
            const homeWon = g.winner === "home";
            const ht = topScorer(g.homeBox);
            const at = topScorer(g.awayBox);
            return (
              <div key={i} className="px-4 py-3">
                <div className="flex items-center gap-3">
                  <span className="font-display text-xs font-bold text-zinc-500 w-12 shrink-0">G{i + 1}</span>
                  <span className={`flex-1 text-sm font-bold truncate ${homeWon ? "text-white" : "text-zinc-500"}`}>
                    {home.name}
                  </span>
                  <span className="font-display text-sm font-black tabular-nums shrink-0">
                    <span className={homeWon ? "text-orange-400" : "text-zinc-500"}>{g.homeTotal}</span>
                    <span className="text-zinc-700 mx-1.5">-</span>
                    <span className={!homeWon ? "text-orange-400" : "text-zinc-500"}>{g.awayTotal}</span>
                  </span>
                  <span className={`flex-1 text-sm font-bold truncate text-right ${!homeWon ? "text-white" : "text-zinc-500"}`}>
                    {away.name}
                  </span>
                  {g.overtime && <span className="text-[10px] text-amber-400 font-bold shrink-0">OT</span>}
                </div>
                {/* Top scorer of each team for this game. Name truncates while
                    the points stay pinned (shrink-0) so they're always visible. */}
                <div className="flex items-center gap-3 mt-1.5 pl-12 text-[11px] text-zinc-500">
                  <span className="flex-1 min-w-0 flex items-center gap-1">
                    <span className="shrink-0">🏀</span>
                    <span className="truncate">{shortScorer(ht.name)}</span>
                    <span className="font-bold text-zinc-300 shrink-0">{ht.pts}</span>
                  </span>
                  <span className="flex-1 min-w-0 flex items-center justify-end gap-1">
                    <span className="font-bold text-zinc-300 shrink-0">{at.pts}</span>
                    <span className="truncate">{shortScorer(at.name)}</span>
                    <span className="shrink-0">🏀</span>
                  </span>
                </div>
              </div>
            );
          })}
        </div>

        <button
          onClick={() =>
            shareToX(
              `🏀 ${home.name} ${wins.home}–${wins.away} ${away.name}\n${winnerName} takes the series! Simulated by #NBATeamCraft`,
              {
                home: home.name,
                away: away.name,
                hs: wins.home,
                as: wins.away,
                kind: "series",
                games: games.map((g) => `${g.homeTotal}-${g.awayTotal}`).join(","),
                tops: encodeTops(games),
              }
            )
          }
          className="w-full py-3 rounded-xl bg-orange-500 hover:bg-orange-400 active:bg-orange-600 text-white font-bold text-sm transition-colors"
        >
          Share on 𝕏
        </button>
        <PostToSimFeedButton payload={{
          kind: "matchup",
          title: `⚔️ ${winnerName} wins the series!`,
          subtitle: `Match · Series · ${wins.home}-${wins.away}`,
        }} />
        {sourceTeamId && !posted && (
          <button
            onClick={async () => {
              setPosting(true);
              try {
                const isHome = home.id === sourceTeamId;
                const result = winner === (isHome ? "home" : "away") ? "win" : "loss";
                const scoreFor = isHome ? wins.home : wins.away;
                const scoreAgainst = isHome ? wins.away : wins.home;
                await fetch(`/api/teams/${sourceTeamId}/simulations`, {
                  method: "POST",
                  headers: { "Content-Type": "application/json" },
                  body: JSON.stringify({
                    type: "match",
                    result_data: {
                      result,
                      score_for: scoreFor,
                      score_against: scoreAgainst,
                      opponent_name: isHome ? away.name : home.name,
                      mode: "series",
                    },
                  }),
                });
                setPosted(true);
                setTimeout(() => router.push(`/team/${sourceTeamId}`), 800);
              } catch {
                setPosting(false);
              }
            }}
            disabled={posting}
            className="w-full py-3 rounded-xl bg-orange-500/20 border border-orange-500/40 hover:bg-orange-500/30 text-orange-300 font-bold text-sm transition-colors disabled:opacity-50"
          >
            {posted ? "✓ Posted!" : posting ? "Posting…" : "📌 Post to Team Page"}
          </button>
        )}
        <button
          onClick={onRematch}
          className="w-full py-3 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-white font-bold text-sm transition-colors"
        >
          🔄 Rematch (Same Teams)
        </button>
        <button
          onClick={onReset}
          className="w-full py-3 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-white font-bold text-sm transition-colors"
        >
          ⚔️ New Matchup
        </button>
        <BuildOwnTeamCTA />
      </div>
    </div>
  );
}

// ── Series playback (game-by-game animated reveal) ──────────────────
// Plays the already-computed series one game at a time so the result builds
// tension instead of dropping all at once — designed to be screen-recorded
// for short-form video. When playback finishes it hands off to SeriesResult,
// which is the unchanged final/share screen.

function usePrefersReducedMotion(): boolean {
  const [reduce, setReduce] = useState(false);
  useEffect(() => {
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    setReduce(mq.matches);
    const on = () => setReduce(mq.matches);
    mq.addEventListener("change", on);
    return () => mq.removeEventListener("change", on);
  }, []);
  return reduce;
}

// Eased count-up toward `target`; only runs while `active`.
function useCountUp(target: number, active: boolean, duration = 1000): number {
  const [val, setVal] = useState(0);
  useEffect(() => {
    if (!active) return;
    let raf = 0;
    const start = performance.now();
    const tick = (now: number) => {
      const t = Math.min(1, (now - start) / duration);
      const eased = 1 - Math.pow(1 - t, 3); // ease-out cubic
      setVal(Math.round(eased * target));
      if (t < 1) raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [target, active, duration]);
  return val;
}

function ScoreNum({ value, animate }: { value: number; animate: boolean }) {
  const shown = useCountUp(value, animate);
  return <>{animate ? shown : value}</>;
}

function PlayGameRow({
  g,
  index,
  home,
  away,
  animate,
  settled,
}: {
  g: GameResult;
  index: number;
  home: SimMeta;
  away: SimMeta;
  animate: boolean;
  settled: boolean;
}) {
  const homeWon = g.winner === "home";
  // While the active row is still counting up, keep both sides neutral so the
  // winner only "pops" once the final score lands.
  const decided = settled || !animate;
  const ht = topScorer(g.homeBox);
  const at = topScorer(g.awayBox);
  return (
    <div
      className={`px-4 py-3 gp-rise transition-colors ${
        animate ? "bg-orange-500/5 ring-1 ring-inset ring-orange-500/30 rounded-xl" : ""
      }`}
    >
      <div className="flex items-center gap-3">
        <span className="font-display text-xs font-bold text-zinc-500 w-12 shrink-0">G{index + 1}</span>
        <span className={`flex-1 text-sm font-bold truncate ${decided && homeWon ? "text-white" : "text-zinc-500"}`}>
          {home.name}
        </span>
        <span className="font-display text-sm font-black tabular-nums shrink-0">
          <span className={decided && homeWon ? "text-orange-400" : "text-zinc-400"}>
            <ScoreNum value={g.homeTotal} animate={animate && !settled} />
          </span>
          <span className="text-zinc-700 mx-1.5">-</span>
          <span className={decided && !homeWon ? "text-orange-400" : "text-zinc-400"}>
            <ScoreNum value={g.awayTotal} animate={animate && !settled} />
          </span>
        </span>
        <span className={`flex-1 text-sm font-bold truncate text-right ${decided && !homeWon ? "text-white" : "text-zinc-500"}`}>
          {away.name}
        </span>
        {g.overtime && decided && <span className="text-[10px] text-amber-400 font-bold shrink-0">OT</span>}
      </div>
      {decided && (
        <div className="flex items-center gap-3 mt-1.5 pl-12 text-[11px] text-zinc-500 gp-fade">
          <span className="flex-1 min-w-0 flex items-center gap-1">
            <span className="shrink-0">🏀</span>
            <span className="truncate">{shortScorer(ht.name)}</span>
            <span className="font-bold text-zinc-300 shrink-0">{ht.pts}</span>
          </span>
          <span className="flex-1 min-w-0 flex items-center justify-end gap-1">
            <span className="font-bold text-zinc-300 shrink-0">{at.pts}</span>
            <span className="truncate">{shortScorer(at.name)}</span>
            <span className="shrink-0">🏀</span>
          </span>
        </div>
      )}
    </div>
  );
}

// Per-game pacing (ms): time the scores count up, then time before the next
// game drops in.
const SETTLE_MS = 1100;
const ADVANCE_MS = 2700;

function SeriesPlayback(props: {
  home: SimMeta;
  away: SimMeta;
  games: GameResult[];
  wins: { home: number; away: number };
  winner: "home" | "away";
  onReset: () => void;
  onRematch: () => void;
  sourceTeamId?: string | null;
}) {
  const { home, away, games } = props;
  const reduce = usePrefersReducedMotion();
  const [current, setCurrent] = useState(0); // index of the game animating now
  const [settled, setSettled] = useState(false); // active game's score landed?
  const [done, setDone] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);

  // Drive the reveal: settle the active game, then advance to the next.
  useEffect(() => {
    if (done) return;
    if (current >= games.length) {
      const t = setTimeout(() => setDone(true), reduce ? 0 : 900);
      return () => clearTimeout(t);
    }
    setSettled(false);
    const t1 = setTimeout(() => setSettled(true), reduce ? 0 : SETTLE_MS);
    const t2 = setTimeout(() => setCurrent((c) => c + 1), reduce ? 250 : ADVANCE_MS);
    return () => {
      clearTimeout(t1);
      clearTimeout(t2);
    };
  }, [current, done, games.length, reduce]);

  // Keep the newest game in view as the list grows.
  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: reduce ? "auto" : "smooth", block: "end" });
  }, [current, settled, reduce]);

  // Running series score: count games whose reveal has completed. The active
  // game joins the tally the moment its score settles, so the number pops in
  // sync with the winner lighting up.
  const tally = useMemo(() => {
    let h = 0;
    let a = 0;
    const upto = Math.min(settled ? current + 1 : current, games.length);
    for (let i = 0; i < upto; i++) {
      if (games[i].winner === "home") h++;
      else a++;
    }
    return { h, a };
  }, [current, settled, games]);

  if (done) return <SeriesResult {...props} />;

  const leadHome = tally.h > tally.a;
  const leadAway = tally.a > tally.h;

  return (
    <div className="fixed inset-0 z-50 bg-zinc-950 overflow-y-auto">
      <style>{`
        @keyframes gp-rise { 0% { transform: translateY(16px); opacity: 0 } 100% { transform: translateY(0); opacity: 1 } }
        @keyframes gp-pop  { 0% { transform: scale(.55); opacity: 0 } 60% { transform: scale(1.18) } 100% { transform: scale(1); opacity: 1 } }
        @keyframes gp-fade { 0% { opacity: 0 } 100% { opacity: 1 } }
        .gp-rise { animation: gp-rise .45s cubic-bezier(.2,.7,.2,1) both }
        .gp-pop  { animation: gp-pop  .5s  cubic-bezier(.2,.9,.3,1.25) both }
        .gp-fade { animation: gp-fade .4s ease both }
        @media (prefers-reduced-motion: reduce) { .gp-rise,.gp-pop,.gp-fade { animation: none } }
      `}</style>

      <AppHeader actions={
        <>
          <button onClick={props.onReset} className="text-xs font-bold text-zinc-400 hover:text-white transition-colors">← Back</button>
          <button
            onClick={() => {
              gtm.seriesPlaybackSkip({ games_revealed: Math.min(current + 1, games.length), games_total: games.length });
              setDone(true);
            }}
            className="text-[11px] font-bold text-zinc-500 hover:text-white transition-colors"
          >
            Skip ⏭
          </button>
        </>
      } />

      <div className="max-w-lg mx-auto px-4 py-8 space-y-5">
        <div className="flex items-center justify-between">
          <p className="font-display text-xs font-bold text-orange-400 uppercase tracking-[0.3em]">
            Series · Best of 7
          </p>
        </div>

        {/* Live series scoreboard — pops on each change */}
        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-5">
          <div className="flex items-center justify-between gap-3">
            <div className="flex-1 min-w-0 text-center">
              <p className={`text-xs font-bold truncate ${leadHome ? "text-white" : "text-zinc-400"}`}>{home.name}</p>
              <p key={`h-${tally.h}`} className={`gp-pop font-display text-6xl font-black mt-1 ${leadHome ? "text-orange-400" : "text-zinc-500"}`}>
                {tally.h}
              </p>
            </div>
            <span className="font-display text-lg font-black text-zinc-600 shrink-0">–</span>
            <div className="flex-1 min-w-0 text-center">
              <p className={`text-xs font-bold truncate ${leadAway ? "text-white" : "text-zinc-400"}`}>{away.name}</p>
              <p key={`a-${tally.a}`} className={`gp-pop font-display text-6xl font-black mt-1 ${leadAway ? "text-orange-400" : "text-zinc-500"}`}>
                {tally.a}
              </p>
            </div>
          </div>
          <p className="text-center text-[11px] text-zinc-500 mt-4 pt-3 border-t border-zinc-800 font-display uppercase tracking-[0.2em]">
            {current < games.length ? `Game ${Math.min(current + 1, games.length)} of ${games.length}` : "Series complete"}
          </p>
        </div>

        {/* Games revealed so far (active one animates) */}
        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl divide-y divide-zinc-800/60">
          {games.slice(0, Math.min(current + 1, games.length)).map((g, i) => (
            <PlayGameRow
              key={i}
              g={g}
              index={i}
              home={home}
              away={away}
              animate={i === current}
              settled={i === current ? settled : true}
            />
          ))}
        </div>
        <div ref={endRef} />
      </div>
    </div>
  );
}

export default function MatchupClient({ initialTeams }: { initialTeams?: import("@/components/sim/TeamPicker").TeamPick[] }) {
  const router = useRouter();
  const params = useSearchParams();

  // Pre-select the HOME team when arriving from a team page / result page.
  const [home, setHome] = useState<TeamPick | null>(() => {
    const id = params.get("homeTeamId");
    if (!id) return null;
    return {
      id,
      name: params.get("homeName") ?? "Selected Team",
      overall: Number(params.get("homeOverall")) || 0,
      tier: params.get("homeTier") ?? "C",
      is_sandbox: params.get("homeSandbox") === "1",
      created_at: "",
    };
  });
  const [away, setAway] = useState<TeamPick | null>(null);
  const [mode, setMode] = useState<"single" | "series">("single");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [sim, setSim] = useState<SimResponse | null>(null);

  const simulate = useCallback(async () => {
    if (!home || !away) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/matchup/simulate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ homeTeamId: home.id, awayTeamId: away.id, mode }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error ?? "Failed to simulate");
      setSim(json as SimResponse);
      // If a random pick was used, lock in the resolved team so a "Rematch
      // (Same Teams)" replays the actual teams instead of re-randomizing.
      if (home.id === RANDOM_ID) {
        setHome({ id: json.home.id, name: json.home.name, overall: json.home.overall, tier: json.home.tier, is_sandbox: false, created_at: "" });
      }
      if (away.id === RANDOM_ID) {
        setAway({ id: json.away.id, name: json.away.name, overall: json.away.overall, tier: json.away.tier, is_sandbox: false, created_at: "" });
      }
      const winnerName =
        json.mode === "series"
          ? json.seriesWinner === "home" ? home.name : away.name
          : json.result.winner === "home" ? home.name : away.name;
      gtm.simulateMatch({ home_team: home.name, away_team: away.name, mode, winner: winnerName });
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to simulate");
    } finally {
      setLoading(false);
    }
  }, [home, away, mode]);

  const reset = () => setSim(null);

  // ── Result overlays ──────────────────────────────────────────────
  if (sim?.mode === "single" && home && away) {
    const r = sim.result;
    const winnerName = r.winner === "home" ? sim.home.name : sim.away.name;
    const shareText = `🏀 ${sim.home.name} ${r.homeTotal}–${r.awayTotal} ${sim.away.name}\n${winnerName} wins! Simulated by #NBATeamCraft`;
    const singleSourceId = (() => {
      const sp = params.get("homeTeamId");
      return sp && sp !== RANDOM_ID ? sp : null;
    })();
    return (
      <ExhibitionMatch
        userTeamName={sim.home.name}
        userOverall={sim.home.overall}
        userTier={sim.home.tier}
        opponent={{ id: sim.away.id, name: sim.away.name, overall: sim.away.overall, tier: sim.away.tier }}
        result={sim.result}
        sessionRecord={{ wins: 0, losses: 0 }}
        onRematch={simulate}
        rematchLabel="🔄 Rematch (Same Teams)"
        onNewMatchup={reset}
        onClose={reset}
        onBack={reset}
        defaultShowBox
        onShare={() =>
          shareToX(shareText, {
            home: sim.home.name,
            away: sim.away.name,
            hs: r.homeTotal,
            as: r.awayTotal,
            kind: "single",
          })
        }
        footer={
          <>
            <PostToSimFeedButton payload={{
              kind: "matchup",
              title: `⚔️ ${r.winner === "home" ? sim.home.name : sim.away.name} def. ${r.winner === "home" ? sim.away.name : sim.home.name}`,
              subtitle: "Match · Single",
            }} />
            {singleSourceId && (
              <PostToTeamButton
                teamId={singleSourceId}
                payload={{
                  type: "match",
                  result_data: {
                    result: r.winner === "home" ? "win" : "loss",
                    score_for: r.homeTotal,
                    score_against: r.awayTotal,
                    opponent_name: sim.away.name,
                    mode: "single",
                  },
                }}
                onPosted={() => router.push(`/team/${singleSourceId}`)}
              />
            )}
          </>
        }
        bottomCta={<BuildOwnTeamCTA />}
      />
    );
  }

  if (sim?.mode === "series") {
    const sp = params.get("homeTeamId");
    const sourceId = sp && sp !== RANDOM_ID ? sp : null;
    return (
      <SeriesPlayback
        // Remount per simulation so a rematch replays from Game 1.
        key={`${sim.home.id}-${sim.away.id}-${sim.games.length}-${sim.seriesWins.home}-${sim.seriesWins.away}`}
        home={sim.home}
        away={sim.away}
        games={sim.games}
        wins={sim.seriesWins}
        winner={sim.seriesWinner}
        onReset={reset}
        onRematch={simulate}
        sourceTeamId={sourceId}
      />
    );
  }

  // ── Picker ───────────────────────────────────────────────────────
  return (
    <div className="min-h-screen bg-zinc-950 text-white">
      <AppHeader actions={
        <button onClick={() => router.back()} className="text-xs font-bold text-zinc-400 hover:text-white transition-colors">← Back</button>
      } />

      <div className="max-w-lg mx-auto px-4 py-6 space-y-6">
        <p className="text-center text-sm text-zinc-400">
          Pit any two lineups against each other — Dream Draft or Roster Builder.
        </p>

        <div className="flex items-start gap-3">
          <TeamPicker label="Home" accent="text-orange-400" selected={home} onSelect={setHome} initialTeams={initialTeams} />
          <div className="pt-7 shrink-0">
            <span className="font-display text-lg font-black text-zinc-600">VS</span>
          </div>
          <TeamPicker label="Away" accent="text-sky-400" selected={away} onSelect={setAway} initialTeams={initialTeams} />
        </div>

        {/* Mode toggle */}
        <div className="flex bg-zinc-900 border border-zinc-800 rounded-xl p-1">
          {([
            { key: "single", label: "Single Game" },
            { key: "series", label: "Series (4-Win)" },
          ] as const).map((m) => (
            <button
              key={m.key}
              onClick={() => setMode(m.key)}
              className={`flex-1 py-2 rounded-lg text-sm font-bold transition-colors ${
                mode === m.key ? "bg-orange-500 text-white" : "text-zinc-400 hover:text-white"
              }`}
            >
              {m.label}
            </button>
          ))}
        </div>

        {error && <p className="text-center text-sm text-red-400">{error}</p>}

        <button
          onClick={simulate}
          disabled={!home || !away || loading}
          className="w-full py-4 rounded-xl bg-orange-500 hover:bg-orange-400 active:bg-orange-600 disabled:opacity-40 disabled:cursor-not-allowed text-white font-display font-black text-base uppercase tracking-widest transition-colors flex items-center justify-center gap-2"
        >
          {loading ? (
            <>
              <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              {mode === "series" ? "Playing series…" : "Simulating…"}
            </>
          ) : (
            "⚔️ Simulate"
          )}
        </button>

        <div className="pt-2">
          <p className="text-center text-xs text-zinc-600 mb-2">
            Can&apos;t find the perfect roster?
          </p>
          <BuildOwnTeamCTA />
        </div>

        <SimCrossLinks current="match" />
      </div>
    </div>
  );
}
